sync_config:
  branch: csharplus_add_pip
  email: null
  remote_repo_link: git@github.com:csharplus/mage-ai.git
  repo_path: null
  ssh_private_key_secret_name: mage_git_ssh_private_key_b64
  ssh_public_key_secret_name: mage_git_ssh_public_key_b64
  sync_on_pipeline_run: false
  type: null
  username: null
